# .github/actions/setup-node/action.yml
name: "Setup Node.js Environment"
description: "Checks out code, sets up Node.js, and installs dependencies with caching"

runs:
    using: "composite"
    steps:
        - name: "Checkout"
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Setup Node.js (with Yarn cache)
          uses: actions/setup-node@v4
          with:
              node-version: "22"
              cache: "yarn"

        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          shell: bash
          run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

        - name: Cache Dependencies
          uses: actions/cache@v4
          id: yarn-cache
          with:
              path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                  ${{ runner.os }}-yarn-

        - name: Cache node_modules
          uses: actions/cache@v4
          id: node-modules-cache
          with:
              path: node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                  ${{ runner.os }}-node-modules-

        - name: Install dependencies
          if: steps.node-modules-cache.outputs.cache-hit != 'true'
          shell: bash
          run: yarn install --frozen-lockfile --prefer-offline
